# Generated by Django 6.0.1 on 2026-01-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0002_alter_staffmodel_created_at'),
        ('vehicle_logs', '0004_remove_checkinmodel_image_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('AUTO', 'Automatic(Vehicle Entry)'), ('MANUAL', 'Manual Entry')], default='AUTO', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendace_first_checkin', to='vehicle_logs.checkinmodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendace_records', to='staffs.staffmodel')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'date'), name='unique_staff_attendance')],
            },
        ),
    ]
