# Generated by Django 6.0.1 on 2026-01-28 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
        ('staffs', '0002_alter_staffmodel_created_at'),
        ('vehicle_logs', '0004_remove_checkinmodel_image_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecordmodel',
            name='first_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_first_checkin', to='vehicle_logs.checkinmodel'),
        ),
        migrations.AlterField(
            model_name='attendancerecordmodel',
            name='source',
            field=models.CharField(choices=[('AUTO', 'Automatic(Vehicle Entry)'), ('MANUAL', 'Manual Entry')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecordmodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staffs.staffmodel'),
        ),
    ]
