# Generated by Django 6.0.1 on 2026-01-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='university_id',
            new_name='staff_number',
        ),
    ]
