# Generated by Django 6.0.1 on 2026-01-31 13:53

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Define your groups
    finance_group, _ = Group.objects.get_or_create(name='Finance')
    security_group, _ = Group.objects.get_or_create(name='Security')

    # Optional: Assign specific permissions automatically
    # view_allowance = Permission.objects.get(codename='view_allowancemodel')
    # finance_group.permissions.add(view_allowance)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_university_id_customuser_staff_number'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
