# Generated by Django 6.0.1 on 2026-01-20 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('gate', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('image_part', models.CharField(max_length=100)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staffmodel')),
            ],
        ),
    ]
