# Generated by Django 6.0.1 on 2026-01-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_logs', '0002_alter_checkinmodel_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinmodel',
            name='plate_number',
            field=models.CharField(max_length=10),
        ),
    ]
