# Generated by Django 6.0.1 on 2026-01-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_alter_staffmodel_created_at'),
        ('vehicle_logs', '0003_alter_checkinmodel_plate_number'),
        ('vehicles', '0003_alter_vehiclemodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinmodel',
            name='image_part',
        ),
        migrations.RemoveField(
            model_name='checkinmodel',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='checkinmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_logs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='checkinmodel',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.staffmodel'),
        ),
        migrations.AddField(
            model_name='checkinmodel',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
