# Generated by Django 6.0.1 on 2026-01-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehiclemodel_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
