# Generated by Django 6.0.1 on 2026-01-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('vehicle_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('source_log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_logs.checkinmodel')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staffmodel')),
            ],
        ),
    ]
