# Generated by Django 6.0.1 on 2026-01-24 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowances', '0001_initial'),
        ('staffs', '0002_alter_staffmodel_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowancemodel',
            options={'ordering': ['-month']},
        ),
        migrations.RemoveField(
            model_name='allowancemodel',
            name='source_log_id',
        ),
        migrations.RemoveField(
            model_name='allowancemodel',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='allowancemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allowancemodel',
            name='days_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allowancemodel',
            name='rate_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='allowancemodel',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='staffs.staffmodel'),
        ),
        migrations.AlterField(
            model_name='allowancemodel',
            name='month',
            field=models.DateField(db_index=True, help_text='Use first day of month, e.g. 2026-01-01'),
        ),
        migrations.AlterField(
            model_name='allowancemodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='allowancemodel',
            constraint=models.UniqueConstraint(fields=('staff', 'month'), name='uniq_staff_month_allowance'),
        ),
    ]
