# Generated by Django 6.0.1 on 2026-01-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowances', '0002_alter_allowancemodel_options_and_more'),
        ('staffs', '0002_alter_staffmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancemodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='staffs.staffmodel'),
        ),
    ]
